### ISSUE TITLE
[FEATURE]: <YTMD>

### ISSUE THREAD

**Issue by SgtKnolle** [XeroxDev/YTMD-StreamDeck#144] opened 2024-11-29 23:07 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

How can i use Youtube Music Desktop. I cant find the Host of YTMD for integrate in my Streamdeck

**Comment by XeroxDev** [comment] 2024-12-18 20:15
Sorry for the late response.

This seems to be a /duplicate of #140

Please follow the [How to](https://help.xeroxdev.de/en/stream-deck/ytmd/home#h-5-how-to-use-it) for a detailed guide.

> This also contains images, if you press the `show me` button ![image](https://private-user-images.githubusercontent.com/10864620/371526850-93ccea4c-2d27-4b9e-a10a-06c309d54efa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTMwOTYsIm5iZiI6MTczNDU1Mjc5NiwicGF0aCI6Ii8xMDg2NDYyMC8zNzE1MjY4NTAtOTNjY2VhNGMtMmQyNy00YjllLWExMGEtMDZjMzA5ZDU0ZWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIwMTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1Y2NhN2JlZjEwMWZkZTg0NjQxN2YzOTRlMzViZDZmMzEyMzViOTRmYzk0YjNlODBhYTNiNTQ0NzFjNjExNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Uhz6y1ZHO9IiZotCZtNUN-ZOIQWmjvHUSKqYDw0xOwk)
> 
> On step 4. there's also an image with the default credentials Host: 127.0.0.1 Port: 9863
> 
> If this resolved the issue, feel free to close it or give feedback, if something still not working regarding this issue.

**Closed** 2024-12-18 20:15 UTC
Labels: Type: Enhancement, Type: Duplicate
