### ISSUE TITLE
[Bug]: Plugin can't control v2.0.0 of YTMD anymore with teh Companion connection instead of Remote control system

### ISSUE THREAD

**Issue by digihash** [XeroxDev/YTMD-StreamDeck#97] opened 2024-02-05 16:52 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

The plugin doesn't connect with YTMD anymore since version 2.0.0. I guess because now it's using the Companion connections instead of the old Remote control system.

### Expected Behavior

That the plugin works as before but connected to Companion in v2.0.0

### Steps To Reproduce

1. install v2.0.0 of YTMD on Windows
2. Enable Companion in settings/integrations of YTMD
3. click the play button on stream deck
4. Nothing works and you see the exclamation mark.

### OS

Windows

### OS Version

11

### Plugin Version

v1.7.0

### YTMDesktop Version

v2.0.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2024-02-05 18:05
Hello and thank you for opening this issue.

This is known and I'm already working on the v2 migration.

Also this is an /duplicate of #85 (the pinned issue). For further information please refer to #85 because this kinda is the "V2 Master Ticket".

**Closed by XeroxDev** 2024-02-05 18:05 UTC
Labels: Type: Bug, Type: Duplicate

**Comment by digihash** [comment] 2024-02-06 08:20
Sorry, didn't see that other issue

**Comment by tjwrona** [comment] 2024-02-12 19:33
@XeroxDev I have updated to the latest version and the "authorize" button in the streamdeck plugin doesn't seem to work. I went into the YTMusic Desktop settings and made sure I turned on the companion server and enabled companion authorization but when I click the button nothing happens.

**Comment by XeroxDev** [comment] 2024-02-12 20:58
Yeah. I made a mistake while building the plugin (no issues with the source code, just the artifact / plugin file).

I've uploaded the correct file now and everything should work.

The download is (still) here https://github.com/XeroxDev/YTMD-StreamDeck/releases/tag/v2.0.0

Sorry!
