### ISSUE TITLE
[FEATURE]: Set autoplay playlist

### ISSUE THREAD

**Issue by emilioagustin** [XeroxDev/YTMD-StreamDeck#42] opened 2022-02-15 09:30 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

I will like to select a custom playlist for playing specific music from Stream deck

Thanks and great work

**Comment by XeroxDev** [comment] 2022-02-15 09:53
YTMDesktop already supports this feature standalone (without the need of plugins). You just have to create a action that opens ytmd://play/<VideoID>/<PlaylistID>. <VideoID> is your desired video Id (the entry / first video in the Playlist as example) and <PlaylistID> is the playlist id.

**Comment by XeroxDev** [comment] 2022-02-15 09:54
YTMDesktop already supports this feature standalone (without the need of plugins). You just have to create a action that opens ``ytmd://play/<VideoID>/<PlaylistID>``. ``<VideoID>`` is your desired video Id (the entry / first video in the Playlist as example) and ``<PlaylistID>`` is the playlist id.

**Comment by emilioagustin** [comment] 2022-02-15 09:58
Thanks my friend but this command crashes, I have put this:

ytmd://play/PLHrFvO1TALRjaDVjHEIku7PfBYvfg-Wph

And when we open the app throws this:

![image](https://user-images.githubusercontent.com/9576745/154037931-0f7a3c14-144e-4a06-b775-f28b4257cce5.png)
![image](https://user-images.githubusercontent.com/9576745/154037960-e721756d-20c6-4134-ad0e-20c7fbbd054a.png)

Other thing its that you can´t use this command automatically by Stream deck because Chrome throws a popup for confirming open ytmd app

![image](https://user-images.githubusercontent.com/9576745/154038256-23127f65-c422-45a2-997d-469771d712ca.png)

**Comment by XeroxDev** [comment] 2022-02-15 11:29
This error message is a known bug in the YTMDesktop Application (see ytmdesktop/ytmdesktop#464) but got (as far as I know) fixed in their Beta / Nightly release (I would recommend to download the latest (nightly/pre-)release in their [release tab](https://github.com/ytmdesktop/ytmdesktop/releases).

About the "open it instantly in the YTMDesktop app", I've to ask the developers of YTMDesktop, if they have a workaround for you.

**Comment by emilioagustin** [comment] 2022-02-15 11:56
Ok, I have downloaded the nightly version and this bug its fixed. I am waiting for your response about the popup.

Thanks bro!

**Comment by emilioagustin** [comment] 2022-02-15 13:50
I have ran the action from the Windows run app and works perfect but it doesnt work like it should. I cant call a run script from stream deck. I have tested the API but fails to set the playlist, only works for query and other features.

Waiting for news
Thanks a lot!

**Comment by XeroxDev** [comment] 2022-02-15 15:24
YTMDesktop is currently working on expanding the API for third-party developers (like me) and one of the new endpoints are for this kind of features. If it is getting released (see ytmdesktop/ytmdesktop#845) I'll hop on a feature to simplify it. In the meantime I set this issue to "blocked" and we've to use the workaround with the `ytmd://play` url and wait for it to release.

**Comment by emilioagustin** [comment] 2022-02-15 15:28
Perfect my friend, waiting for news!!

**Comment by XeroxDev** [comment] 2024-02-10 18:16
Hey! I'm currently working on the V2 support and tried to implement your suggested feature.

Sadly I've to inform you, that it's not possible to implement this in the current plugin architecture. I've tried it in multiple ways but it seems no matter what I try, I can't use custom URI schemes (the only thing YTMDesktop supports to do something like that). Elgato seems to block it and like mentioned before, YTMDestkop, even in V2, doesn't support such things through their API.

That's why I've considered to /close this issue for now. I'll re-investigate it in the future to look if support gets added.

**Closed by XeroxDev** 2024-02-10 18:16 UTC
Labels: Type: Enhancement, Status: Blocked

**Comment by Fefedu973** [comment] 2024-03-10 14:34
I hope that you found a solution ! thanks for everything

**Comment by XeroxDev** [comment] 2024-03-10 14:52
> I hope that you found a solution ! thanks for everything

Nothing changed since I closed this sadly. Until they add a possibility, it's not possible.

**Comment by Fefedu973** [comment] 2024-03-10 15:08
> > I hope that you found a solution ! thanks for everything
> 
> Nothing changed since I closed this sadly. Until they add a possibility, it's not possible.

Have you asked the YTMD devs if it could be implemented?

**Comment by XeroxDev** [comment] 2024-03-10 15:09
Sure. They confirmed they will implement it, but not when.

**Comment by Fefedu973** [comment] 2024-03-10 15:16
Ok nice. Thanks !
