### ISSUE TITLE
[Bug]: Volume up and Voolume down button not working

### ISSUE THREAD

**Issue by 1976Stevie** [XeroxDev/YTMD-StreamDeck#86] opened 2023-10-03 08:41 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When I add the volume up or the volume down button to the Stream deck, both don't work.

### Expected Behavior

Volume up to increase volume and volume down to decrease volume.

### Steps To Reproduce

1. Add both the volume up and volume down button to the Stream Deck
2. Press either button and both don't work as intended.

### OS

Windows

### OS Version

10

### Plugin Version

v1.7.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2023-10-03 20:08
This seems to be a /duplicate of #28

**Closed by XeroxDev** 2023-10-03 20:08 UTC
Labels: Type: Bug, Type: Duplicate
