### ISSUE TITLE
Dudas[QUESTION]: <title>

### ISSUE THREAD

**Issue by KillerSoul82** [XeroxDev/YTMD-StreamDeck#56] opened 2022-11-13 13:12 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Soy nuevo usando esta app pero la quiero controlar con mi stream deck pero no consigo hacerlo con el pluggin de streamdeck

**Comment by XeroxDev** [comment] 2022-11-14 21:56
I guess this is a /duplicate of #55 
Please see my answer there.

**Closed by XeroxDev** 2022-11-14 21:56 UTC
Labels: Type: Question, Type: Duplicate
