### ISSUE TITLE
Volume up / down not working

### ISSUE THREAD

**Issue by Ex3CuTioNx3** [XeroxDev/YTMD-StreamDeck#28] opened 2021-08-20 21:04 UTC
Hey,

if I press louder/quieter or mute it shows in YTMD that it is louder but it isn't. Everything works without the louder/quieter and mute function. What can I do to fix? Or is it a global problem?

**Comment by XeroxDev** [comment] 2021-08-21 08:56
Hey. This is a known problem. But I can't to anything to fix this, because this is a issue from YTMD. I've already opened a issue on their repository ytmdesktop/ytmdesktop#786

**Comment by XeroxDev** [comment] 2021-08-30 21:31
I've had contact to the YTMDesktop developer. They will work on it. In the meantime it kinda semi works in v1.14.0 (can be downloaded from their release. But attention! It's a pre-release!

**Comment by sneakysandals** [comment] 2021-09-28 07:54
Hi I installed v1.14.0 and can confirm the volume up/down buttons still aren't working for me

**Comment by XeroxDev** [comment] 2021-09-28 10:45
This is really strange. For me and many other peoples it works in v1.14.0. So sadly I can't reproduce it in v1.14.0

Could you send me the following information?


OS:
OS Version: 
Plugin Version:
And a video / gif where you show the device and the YTMDesktop application (Volume slider have to be visible!)

**Comment by sneakysandals** [comment] 2021-09-28 10:47
> This is really strange. For me and many other peoples it works in v1.14.0. So sadly I can't reproduce it in v1.14.0
> 
> Could you send me the following information?
> 
> OS:
> OS Version:
> Plugin Version:
> And a video / gif where you show the device and the YTMDesktop application (Volume slider have to be visible!)

It's all good I am using the workaround of using YTM's hotkey feature and binding that to my streamdeck. Seems more reliable at this point in time. Thanks though!

**Comment by XeroxDev** [comment] 2021-09-28 14:27
Okay. Hope it will serve your needs. I really wish I could fix it, but the error is on the YTMDesktop. They also fixed it as I know, but the contributors don't permission to merge something and the maintainer are currently not available.

**Comment by XeroxDev** [comment] 2022-03-31 14:12
I will close this ticket as it works in the latest (pre-)release. v1.13.0 is now no longer supported.

**Closed by XeroxDev** 2022-03-31 14:12 UTC
Labels: Status: Accepted, Status: Blocked, Priority: High, Special: Good first issue

**Comment by Ailithix** [comment] 2024-05-28 21:48
I'm having this issue now and just downloaded it. I'm on Version 2.0.0

**Comment by XeroxDev** [comment] 2024-05-29 20:09
> I'm having this issue now and just downloaded it. I'm on Version 2.0.0

Are you on version 2.x on both (plugin and YTMDesktop)?
