### ISSUE TITLE
[Bug]: Not working with v2.0.0-rc.5?

### ISSUE THREAD

**Issue by virias** [XeroxDev/YTMD-StreamDeck#96] opened 2024-01-15 23:58 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Hello! 

I'm on a fresh installation of [v2.0.0-rc.5](https://github.com/ytmdesktop/ytmdesktop/releases/tag/v2.0.0-rc.5) and using v1.7.0 of this integration. 

I followed [the instructions per the readme](https://github.com/XeroxDev/YTMD-StreamDeck?tab=readme-ov-file#6-how-to-use-it) and at Step 5, going to http://localhost:9863/ only gives `{"message":"Route GET:/ not found","error":"Not Found","statusCode":404}` and the StreamDeck is unable to interact with the app (none of the buttons are working). I have tried running it as admin, checked firewall entries. 

Following the same steps above, if I use the older version of YTMD (v1.13.0), the integration goes through and all of the buttons work _except_ the volume buttons (which is why I tried the nightly version per [one of the other issues](https://github.com/XeroxDev/YTMD-StreamDeck/issues/95) here). 

### Expected Behavior

(above)

### Steps To Reproduce

(above)

### OS

Windows

### OS Version

10

### Plugin Version

v1.7.0

### YTMDesktop Version

v2.0.0-rc.5

### How did you download the software?

GitHub

**Comment by XeroxDev** [comment] 2024-01-16 09:47
Hey and thank you for opening this ticket!

This seems to be a /duplicate of #85

v2 of YTMDesktop isn't supported **yet** but will be soon. I'll contact the developers of YTMDesktop to ask if their endpoints are stable or are still subject to change. If everything is fine, I'll probably start updating this plugin coming weekend.

**Closed by XeroxDev** 2024-01-16 09:47 UTC
Labels: Type: Bug, Type: Duplicate
