### ISSUE TITLE
[Bug]: <Mute, Volume Up/Down not working>

### ISSUE THREAD

**Issue by delerak** [XeroxDev/YTMD-StreamDeck#54] opened 2022-08-09 00:46 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When I use the mute button or the volume up and volume down buttons they don't seem to work properly. When I observe the volume bar in the Music desktop app it shows the bar moving up and down but the volume is not actively changing and muting doesn't appear to mute. 

### Expected Behavior

Expected mute/volume buttons to work.

### Steps To Reproduce

1. Using the buttons on Elgato Stream Deck

### OS

Windows

### OS Version

11

### Plugin Version

v1.6.0 

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by delerak** [comment] 2022-08-09 00:52
Here is a video: https://www.youtube.com/watch?v=-rwnEpVE5Vg

The music might not be able to be heard if it was removed by YT, but that's the general gist of what is happening. The Vol. bar moves and mute shows but it doesn't happen the volume stays the same.

**Comment by XeroxDev** [comment] 2022-08-09 12:38
Hey and thank you for your report!

This is a /duplicate of #28

Please use the information in the mentioned ticket to resolve this issue. In the meanwhile I /close this issue.

Shouldn't those information help, feel free to reopen this ticket.

**Closed by XeroxDev** 2022-08-09 12:38 UTC
Labels: Type: Bug
