### ISSUE TITLE
[Bug]: Volume controls don't work

### ISSUE THREAD

**Issue by ideasculptor** [XeroxDev/YTMD-StreamDeck#72] opened 2023-05-28 04:50 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Volume up and down in streamdeck cause the volume slider in YTMD to move (sometimes - it does get stuck), but the volume doesn't actually change.  Mute in streamdeck also triggers the YTMD UI to do the right thing visually without actually changing the volume of the playback.  In all honesty, this is probably a bug in YTMD.

### Expected Behavior

When volume slider moves, volume changes.  

### Steps To Reproduce

Add volume change actions to streamdeck.
Use them.

### OS

Windows

### OS Version

11

### Plugin Version

v1.7.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2023-05-28 17:20
This seems to be a /duplicate of #28 
Please make sure you're on one of the latest [pre-/nightly releases](https://github.com/ytmdesktop/ytmdesktop/releases), because v1.13.0 isn't supported anymore.

If this issue still persist, feel free to re-open it.

**Closed by XeroxDev** 2023-05-28 17:20 UTC
Labels: Type: Bug, Type: Duplicate
