### ISSUE TITLE
[Bug]: <Cannot pause or play properly>

### ISSUE THREAD

**Issue by shrilex** [XeroxDev/YTMD-StreamDeck#94] opened 2023-12-09 20:42 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When pressing pause/play toggle button. It switches to play my Liked playlist, and i cannot stop it from doing this.

### Expected Behavior

To properly Pause/play on press. Not play my liked playlist of random songs.

### Steps To Reproduce

I am unsure of how to produce. i have reinstalled my YTMD, a version 1.14 nightly, a 2.0, But no matter what i cant get it to work properly anymore, this has started 2 days ago i think. and i havent been doing anything differently then usual.

The 2.0 ofc wouldnt connect. so i looked for a nightly which did connect. but still have the issue.

I also reinstalled the plugin for streamdeck, still have this issue.

### OS

Windows

### OS Version

10

### Plugin Version

1.7

### YTMDesktop Version

1.13 and 1.14.2 

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2023-12-09 20:44
This is a known issue and a /duplicate of #93 

Sadly I can't do anything about it (is an issue with the software itself, not with the plugin). You either have to contact the YTMDesktop Team or try the steps mentioned in the linked issue.

**Closed by XeroxDev** 2023-12-09 20:45 UTC
Labels: Type: Bug, Type: Duplicate
