### ISSUE TITLE
[QUESTION]: v2.0 fully unsupported due to lack of remote server?

### ISSUE THREAD

**Issue by bbible3** [XeroxDev/YTMD-StreamDeck#92] opened 2023-12-05 05:31 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Hi there! I am asking this here because I assume you are very much aware of this -- the latest version of YTMDesktop doesn't seem to have a functional remote server, and with the older versions being deprecated that means this plugin is unable to be used, right? Or is there a workaround somehow? I would love to make use of this!

Thanks!

**Comment by XeroxDev** [comment] 2023-12-05 08:19
Hey! v2 will be supported in the future.
v1.13 is broken, correct.

But you can still use the latest nightly version, that should work just fine.

**Comment by XeroxDev** [comment] 2023-12-09 20:48
I'm gonna /close this issue due to lack of interactivity and because it's kinda a duplicate of #85 

Further progress will be shown there.

**Closed by XeroxDev** 2023-12-09 20:48 UTC
Labels: Type: Question
