### ISSUE TITLE
[QUESTION]: Future with YTMD gone?

### ISSUE THREAD

**Issue by virias** [XeroxDev/YTMD-StreamDeck#111] opened 2024-03-11 15:05 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

Hello! YTMD vanished from GitHub last week, has not returned, and no response from the owner on social media (from what I've seen). Do you have any plans of potentially supporting different desktop apps for the Deck? One alternative I found was https://github.com/th-ch/youtube-music

**Comment by XeroxDev** [comment] 2024-03-11 15:45
Hey! They didn't "vanish", they just have some issues they've to resolve with the github support. For more information you should join their discord (they gave more detailed information there).

And to your other question. As of now I don't have any plans to support other / different kind of youtube music versions / applications.

I'll probably pin this ticket until they resolved the issue.

**Comment by XeroxDev** [comment] 2024-03-11 17:14
Here's an invite link for the [YouTube Music Desktop Discord Server](https://discord.gg/thxYFzKsf3)

**Comment by vladislav-orlovskiy** [comment] 2024-05-06 13:09
@XeroxDev repo is up. but integration seems not working with v2.1.0. I authorized on my mac but play/pause does nothing

**Comment by XeroxDev** [comment] 2024-05-06 13:49
Hey!

I've seen the notification as well and therefor will /close this issue now. 

About your issue @vladislav-orlovskiy could you please open a new ticket (because this isn't the right one for such issues) and share the contents of the  log files located at `~/Library/Logs/ElgatoStreamDeck/`

The correct log files should be called `fun.shiro.ytmd`?

To make sure it's the most recent: Shut down streamdeck, delete (or backup) the `.log` files of ytmd, start the streamdeck again and try to reproduce the issue.

Other possible solutions you should try first are:
- Re-Authorizing
- Rebooting the StreamDeck software.
- Rebooting your Mac
- Uninstalling and installing the plugin again (using the file from the releases tab on this repository)

**Closed by XeroxDev** 2024-05-06 13:49 UTC
Labels: Type: Question
