### ISSUE TITLE
I can not access your app

### ISSUE THREAD

**Issue by fasgamingttv** [XeroxDev/YTMD-StreamDeck#114] opened 2024-04-18 19:33 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Question

I tried to download your app each time coming up with page not found. Has it been taken down??

**Comment by Freddyb888** [comment] 2024-04-18 22:43
SAME HERE

**Comment by lemanutitou** [comment] 2024-04-19 06:12
Bonjour, pareil pour moi.

**Comment by XeroxDev** [comment] 2024-04-25 09:57
This is a /duplicate of #111

Please see the mentioned ticket for more information.

**Closed by XeroxDev** 2024-04-25 09:57 UTC
Labels: Type: Question, Type: Duplicate
