### ISSUE TITLE
[Bug]: Volume Controls, and Mute

### ISSUE THREAD

**Issue by kolproductions** [XeroxDev/YTMD-StreamDeck#53] opened 2022-08-08 03:20 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

Placing the volume actions on Stream Deck.   Each work as expected,  and control the volume bar within YMDesktop App.  
However,  while the graphic shows the volume is increasing, decreasing,  and mutes?   It actually has no effect.    
To force this,  you have to interact with YMDesktop App directly.    Everything else works fine,  just this minor issue.  

### Expected Behavior

Pressing Mute,  I expect the function to actually mute the music.    ( The graphic on streamdeck shows the volume has been turned down to 0%,  but the music hasn't actually been muted.  ) 

Pressing Volume Up,  I expect the volume to increase. 
Pressing Volume Down,  I expect the volume to decrease. 

### Steps To Reproduce

1.  Load the YMDesktop Application
2. Add Mute, Volume Up,  Volume Down to Stream Deck 
3. Connect
4. Play Music Track
5. Press Mute,  Volume Up, Volume Down

### OS

Windows

### OS Version

10

### Plugin Version

v1.6.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2022-08-08 07:59
Hey and thank you for your report! 

This is a /duplicate of #28

Please use the information in the mentioned ticket to resolve this issue. In the meanwhile I /close this issue.

Shouldn't those information help, feel free to reopen this ticket.

**Closed by XeroxDev** 2022-08-08 07:59 UTC
Labels: Type: Bug
