### ISSUE TITLE
[FEATURE]: Add To Playlist

### ISSUE THREAD

**Issue by 0x29a-blink** [XeroxDev/YTMD-StreamDeck#58] opened 2022-12-06 21:28 UTC
### Consent

- [x] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

Click a button to add the currently played song to your playlist. I have read that there was a suggestion for this exact thing but worked around it by using the add to library option. Could it just be an option for us to input our playlist id?

**Comment by XeroxDev** [comment] 2022-12-08 21:47
Duplicate of #50

**Closed** 2022-12-08 21:48 UTC
Labels: Type: Enhancement

**Comment by XeroxDev** [comment] 2022-12-08 21:52
I planned to add both, but closed this issue, because it's still a duplicate, sorry!

But yes, in the future both will be added! If you want to make 100% sure, you can upvote the other suggestion (in #50) or add additional information regarding this there.
