### ISSUE TITLE
Mute and Volume Controls Not Working

### ISSUE THREAD

**Issue by chadblose** [XeroxDev/YTMD-StreamDeck#81] opened 2023-08-17 14:20 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

It appears the mute, volume up, and volume down controls do not work. Volume up and down will move the volume sliders inside the YTMD app, and mute seems to toggle mute yet the audio does not mute or get adjusted at all. I have confirmed it's not my audio setup as if I use the mouse to drag the volume or click the mute button inside YTMD it works fine. I'm not sure if this is a problem with your Stream Deck app or with the YTMD player. All other buttons are working fine for me.

### Expected Behavior

Volume adjustments should not only adjust the UI elements of the YTMD app but also adjust the volume appropriately.

### Steps To Reproduce

1. Press any volume adjustment volume on stream deck.
2. Observe no change in audio volume.
3. Click with mouse on YTMD volume controls
4. Observe proper change in audio adjustment.

### OS

Windows

### OS Version

11

### Plugin Version

1.7.0

### YTMDesktop Version

1.13.0

### How did you download the software?

Elgato Store

### Anything else?

Here's a video of the behavior:
https://photos.app.goo.gl/pXNpDJ2ySAeEB1ts5

**Comment by XeroxDev** [comment] 2023-08-17 14:56
This seems to be a /duplicate of #28 
Please make sure you're on one of the latest [pre-/nightly releases](https://github.com/ytmdesktop/ytmdesktop/releases), because v1.13.0 isn't supported anymore.

If this issue still persist, feel free to re-open it.

**Closed by XeroxDev** 2023-08-17 14:56 UTC
Labels: Type: Bug, Type: Duplicate

**Comment by chadblose** [comment] 2023-08-18 13:12
Confirmed working as expected on 1.14.2
