### ISSUE TITLE
[FEATURE]: Volume Dial Support for Deck+

### ISSUE THREAD

**Issue by killer2239** [XeroxDev/YTMD-StreamDeck#128] opened 2024-07-01 15:57 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

Add Dial support for the Stream Deck + (Plus) version for the volume control of the app. It would be nice if you can use the dial to control the volume up and down levels of the app like the current buttons can do and maybe report its in app volume level. A nice touch to the dial support would be to add support for pressing that dial to either mute it or pause/play the song.

### Alternatives

I know you can use the system volume control plugin and control the windows volume level for the app itself.

**Comment by XeroxDev** [comment] 2024-07-01 19:44
Hello!

This seems to be an /duplicate of #82 

To quote (so you don't have to go into that ticket)

> I sadly have to inform you I can't do anything here, because like mentioned the last time: I don't have an streamdeck+ and probably won't get one in the near future.

**Closed** 2024-07-01 19:44 UTC
Labels: Type: Enhancement, Type: Duplicate
