### ISSUE TITLE
Volume up and down not working at all

### ISSUE THREAD

**Issue by Sk8iie** [XeroxDev/YTMD-StreamDeck#90] opened 2023-11-24 07:07 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

the buttons dont work

### Expected Behavior

the volume should be able to be adjusted from the streamdeck buttons, this is mainly the reason I downloaded this plugin

### Steps To Reproduce

1. Place the icon on the streamdeck
2. Doesnt work after that

### OS

Windows

### OS Version

10

### Plugin Version

v1.7.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

### Anything else?

N/A

**Comment by XeroxDev** [comment] 2023-11-24 08:11
This seems to be a /duplicate of #28 
Please make sure you're on one of the latest [pre-/nightly releases](https://github.com/ytmdesktop/ytmdesktop/releases), because v1.13.0 isn't supported anymore.

If this issue still persist, feel free to re-open it.

**Closed by XeroxDev** 2023-11-24 08:11 UTC
Labels: Type: Bug, Type: Duplicate
