### ISSUE TITLE
[Bug]: Volume actions fails to update actual volume

### ISSUE THREAD

**Issue by Tapawingo** [XeroxDev/YTMD-StreamDeck#63] opened 2023-02-02 12:32 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

When pressing any of the volume controls (volume up, mute, volume down) the YTMD application UI updates to reflect the change but there is no change in actual volume. Uncertain if this is an issue with YTMD integration server or the YTMD Stream Deck Plugin.

### Expected Behavior

When "Volume Up" action is pressed, I expect the audio volume to increase.
When "Volume Down" action is pressed, I expect the audio volume to decrease.
When "Mute" action is pressed, I expect audio to be muted.

### Steps To Reproduce

1. Add "Volume up", "Mute" and "Volume Down" actions to the Stream Deck interface.
2. Change the "Volume Steps" value to 5 on "Volume Up" action and change the "Volume Steps" value to -5 on "Volume Down" action
3. Press "Volume Up", observe YTMD UI update but no audio update
4. Press "Volume Down", observe YTMD UI update but no audio update
5. Press "Mute", observe YTMD UI update but no audio update

### OS

Windows

### OS Version

10

### Plugin Version

v1.6.0

### YTMDesktop Version

v1.13.0

### How did you download the software?

Elgato Store

**Comment by XeroxDev** [comment] 2023-02-02 15:00
Hey and thank you for your report!

This is a /duplicate of #28

Please use the information in the mentioned ticket to resolve this issue. In the meanwhile I /close this issue.

Shouldn't those information help, feel free to reopen this ticket.

**Closed by XeroxDev** 2023-02-02 15:00 UTC
Labels: Type: Bug
