### ISSUE TITLE
[FEATURE]: Bigger album art

### ISSUE THREAD

**Issue by Fefedu973** [XeroxDev/YTMD-StreamDeck#80] opened 2023-08-10 13:06 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Feature

for exemple here instead of having multiple small ones they will be combined and the album art would grow on the 6 (or more) buttons with the text only in the down right corner for exemple

![image](https://github.com/XeroxDev/YTMD-StreamDeck/assets/80718477/39955b4f-7a89-4177-b0fc-fe0495be04a6)

**Comment by XeroxDev** [comment] 2023-08-10 15:09
Hey and thank you for your feedback.

I've to inform you that this is a /duplicate of #59

**Closed by XeroxDev** 2023-08-10 15:09 UTC
Labels: Type: Enhancement, Type: Duplicate
