### ISSUE TITLE
[BUG] Volume Down/UP on release

### ISSUE THREAD

**Issue by Kobunix** [XeroxDev/YTMD-StreamDeck#29] opened 2021-09-03 13:33 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version [e.g. 10]
 - Plugin Version [e.g. v1.0.4.1]
 - YTMD Version [e.g. v1.13.0]
 - Stream Deck Version [e.g. 4.9.2.13193]

**Type of plugin installation**
- [ ] Elgato Plugin Store
- [ ] GitHub repository

**Additional context**

**Comment by XeroxDev** [comment] 2021-09-03 15:55
This is a duplicate of #28

**Closed** 2021-09-03 15:55 UTC
Labels: Type: Bug
