### ISSUE TITLE
[Bug]: The volume buttons aren't changing the volume.

### ISSUE THREAD

**Issue by CyberTheProto** [XeroxDev/YTMD-StreamDeck#95] opened 2023-12-26 22:17 UTC
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.

### Current Behavior

The volume slider is moving to the places that they should be, but it's not changing the volume.

### Expected Behavior

The volume should be changing with the slider

### Steps To Reproduce

1 Download YTMD
2. Place volume control buttons on the Stream Deck buttons
3. Press volume control buttons and check for audible difference.

### OS

Windows

### OS Version

11

### Plugin Version

v1.7.0

### YTMDesktop Version

?

### How did you download the software?

Elgato Store

### Anything else?

I'm pretty new here and this might be a controller issue. it's not a critical error at least in my opinion, but it's an issue that I am experiencing.

**Comment by XeroxDev** [comment] 2023-12-27 00:19
This seems to be a /duplicate of #28 
Please make sure you're on one of the latest [nightly releases](https://github.com/ytmdesktop/ytmdesktop/releases) (v2.x isn't supported right now due to missing api endpoints, it has to be a nightly version like Nightly Release (May 2022)), because v1.13.0 isn't supported anymore.

If this issue still persist, feel free to re-open it.

**Closed by XeroxDev** 2023-12-27 00:19 UTC
Labels: Type: Bug, Type: Duplicate
